### ISSUE TITLE
won't compile in Arduino 1.8.9

### ISSUE THREAD

**Issue by PhinPhin** [mkarawacki/wavesharesharpdustsensor#2]
Hi,

I just tried the library in the latest version of ArduinoIDE for Windows and ended up with:

C:\Program Files (x86)\Arduino\libraries\wavesharesharpdustsensor/WaveshareSharpDustSensor.h:17:2: error: extra qualification 'WaveshareSharpDustSensor::' on member 'WaveshareSharpDustSensor' [-fpermissive]

I edited line 17 in WaveshareSharpDustSensor.h:

`WaveshareSharpDustSensor::WaveshareSharpDustSensor();`

changed it to:

`WaveshareSharpDustSensor();`

and it compiles. First time for me that a error-message helped me in Arduino finding a solution myself. :D
